includes:
  - python-file: functions.py


pipelines:
  - name: check
    description: Newly uploaded patchsets enter this pipeline to receive an initial +/-1 Verified vote from Jenkins.
    success-message: Build succeeded (check pipeline).
    failure-message: Build failed (check pipeline).  For information on how to proceed, see http://docs.openstack.org/infra/manual/developers.html#automated-testing
    manager: IndependentPipelineManager
    source: gerrit
    precedence: normal
    require:
      open: True
      current-patchset: True
    trigger:
      gerrit:
        - event: patchset-created
        - event: change-restored
        - event: comment-added
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*(recheck|reverify)
        - event: comment-added
          require-approval:
            - verified: [-1, -2]
              username: jenkins
          approval:
            - workflow: 1
    success:
      gerrit:
        verified: 1
    failure:
      gerrit:
        verified: -1

  - name: gate
    description: Changes that have been approved by core developers are enqueued in order in this pipeline, and if they pass tests in Jenkins, will be merged.
    success-message: Build succeeded (gate pipeline).
    failure-message: Build failed (gate pipeline).  For information on how to proceed, see http://docs.openstack.org/infra/manual/developers.html#automated-testing
    manager: DependentPipelineManager
    source: gerrit
    precedence: high
    require:
      open: True
      current-patchset: True
      approval:
        - verified: [1, 2]
          username: jenkins
        - workflow: 1
    trigger:
      gerrit:
        - event: comment-added
          approval:
            - workflow: 1
        - event: comment-added
          approval:
            - verified: 1
          username: jenkins
    start:
      gerrit:
        verified: 0
    success:
      gerrit:
        verified: 2
        submit: true
    failure:
      gerrit:
        verified: -2
    window-floor: 20
    window-increase-factor: 2

  - name: merge-check
    description: >
      Each time a change merges, this pipeline verifies that all open changes
      on the same project are still mergeable.
    failure-message: Build failed (merge-check pipeline).
    manager: IndependentPipelineManager
    ignore-dependencies: true
    source: gerrit
    precedence: low
    require:
      approval:
        - verified: [1, 2]
          username: jenkins
    trigger:
      zuul:
        - event: project-change-merged
    merge-failure:
      gerrit:
        verified: -1


project-templates:
  - name: merge-check
    merge-check:
      - noop

  - name: noop-jobs
    check:
      - noop
    gate:
      - noop


jobs:
  - name: ^.*$
    parameter-function: single_use_node


projects:
  - name: openstack-dev/sandbox
    template:
      - name: merge-check
      - name: noop-jobs
